### ISSUE TITLE
Vanishing variables while solving with CBC

### ISSUE THREAD

**Issue by dbokal** [coin-or/pulp#665]
Details for the issue
--------------------

#### I have implemented an approach to a minimum infeasible set of constraints that works rouhly as follows:

1) Assume [C1, C2, C3, ..., C1024] are the constraints of the problem
2) Using bisection, I find the last constraint, such that [C1, ..., CLast] is feasible, but [C1, ..., CLast+1] is infeasible. 
3) Using bisection, I find the first constraint, such that [CFirst, ..., CLast] is feasible, but [CFirst-1, ..., CLast+1] is infeasible. 
4) For each of the remaining constraints Ci, I remove the constraint if [CFirst, Ci-1,Ci+1,...CLast] is infeasible.

As removing these constraints does not bother with the variables, some variables may get redundant, but I do not bother with that. 

#### What did you expect to see?
I expected the above to work just fine, but...

#### What did you see instead?
... what I observed is an exception in the line variables[name].varValue = values[name] of the following function that stores the solution:
    def assignVarsVals(self, values):
        variables = self.variablesDict()
        for name in values:
            if name != "__dummy":
                variables[name].varValue = values[name]
Namely, there were variables that were sent to the solver and stored in the dictionary values[name] so that they could be interpeted, but they did not appear in the variables dictionary. Seemingly they disappeared from the variables dictionary while the problem was being solved.

What I did is simply validate that the variable vas not pruned:
    def assignVarsVals(self, values, warnOnPruning=False):
        variables = self.variablesDict()
        for name in values:
            if name != "__dummy":
                if name not in variables:
                    if warnOnPruning:
                         print(f"Warning: Variable has been pruned: {name}.")
                else:
                    variables[name].varValue = values[name]

Does this make a reasonable and general solution? Should I submit this to pulp? The process of forking etc. is tedious, so I would only go for it if you guys find the solution reasonable.

Useful extra information
-------------------------

The info below often helps, please fill it out if you're able to. :)

#### What operating system are you using?

- [x ] Windows: ( _version:_ 10)
- [ ] Linux: ( _distro:_ ___ )
- [ ] Mac OS: ( _version:_ ___ )
- [ ] Other: ___

#### I'm using python version:

- [ ] 2.7
- [ ] 3.4
- [ ] 3.5
- [ ] 3.6
- [x] Other: 3.10

#### I installed PuLP via:

- [ x] pypi (python -m pip install pulp)
- [ ] github (python -m pip install -U git+https://github.com/coin-or/pulp)
- [ ] Other: ___ (conda?)

#### Did you also

- [ ] Tried out the latest github version: https://github.com/coin-or/pulp
- [x] Searched for an existing similar issue: https://github.com/coin-or/pulp/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by pchtsp** [comment]
Can you please paste the code with some formatting? I cannot read it well. I do not understand if this is an issue or a improvement request?

**Comment by dbokal** [comment]
> Can you please paste the code with some formatting? 
Indeed it was ugly, I did not observe the <> code icon in the edit.

>Also, I do not understand if this is an issue or a feature request.
It is an issue that I had and I (believe) I fixed. It would be great if the fix is consistent with the general behavior of pulp and can be integrated into the main distribution, so that I do not need to refix it next time I update pulp.

If there is a process I need to follow, I am willing to do so, but perhaps it is easiest for an active developer to replace the function I changed in his code and submit it to the main package. Please advise.

**Comment by pchtsp** [comment]
Thanks for the response and the clarification.
I still do not understand the use case or set of circumstances where this happens. Do you have a reproducible example that I can test? Are you editing the model internals? If a variable is not used in a constraint, it should not belong in the model.

Maybe we could do a more consistant pruning before solving so that this exception doesn't happen. But for that we need the reproducible example. Also, so we can add it as a unit test inside the library.
